### ISSUE TITLE
find_signatures1 entered 22 times?

### ISSUE THREAD

**Issue by JohnAGoldsmith** [axanthos/pycrab#7]
scratchpad acts as a list (rather than as a dict, which is what biographies does), and there are 22 occurrences of each word that goes through findignatures1, which is 21 times too many.

**Comment by axanthos** [comment]
This a bit surprising, how did find it out?

**Comment by JohnAGoldsmith** [comment]
I haven't figure this out yet -- hopefully a little later!

**Comment by JohnAGoldsmith** [comment]
We figured this out, it's taken care of.

**Comment by JohnAGoldsmith** [comment]
done.
